ALTER ROLE postgres SET search_path TO E'\\$user', 'public', 'extensions';
ALTER ROLE supabase_admin SET search_path TO '$user', 'public', 'auth', 'extensions';
ALTER ROLE supabase_auth_admin SET search_path TO 'auth';
ALTER ROLE supabase_storage_admin SET search_path TO 'storage';
        DROP FUNCTION IF EXISTS graphql_public.graphql;
        create or replace function graphql_public.graphql(
      ALTER function net.http_get(url text, params jsonb, headers jsonb, timeout_milliseconds integer) SET search_path = net;
      ALTER function net.http_post(url text, body jsonb, params jsonb, headers jsonb, timeout_milliseconds integer) SET search_path = net;
        create or replace function graphql_public.graphql(
COMMENT ON FUNCTION extensions.set_graphql_placeholder() IS 'Reintroduces placeholder function for graphql_public.graphql';
-- Regclass of the table e.g. public.notes
          select realtime.build_prepared_statement_sql('public.notes', '{"id"}'::text[], '{"bigint"}'::text[])
-- Name: arrecadacoes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.arrecadacoes (
    id bigint NOT NULL,
    item_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    transacao_id bigint,
    valor numeric,
    status boolean,
    evento_id bigint DEFAULT '1'::bigint
);


ALTER TABLE public.arrecadacoes OWNER TO postgres;

--
-- Name: arrecadacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.arrecadacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arrecadacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.config (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    "permitirLoja" boolean DEFAULT true,
    "permitirPix" boolean DEFAULT true,
    "chavePix" character varying,
    "nomePix" character varying,
    "cidadePix" character varying,
    endereco text
);


ALTER TABLE public.config OWNER TO postgres;

--
-- Name: config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: eventos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.eventos (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    titulo character varying,
    data date,
    imagem text,
    "corPrincipal" character varying
);


ALTER TABLE public.eventos OWNER TO postgres;

--
-- Name: eventos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.eventos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.eventos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.itens (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    titulo character varying,
    valor double precision,
    link character varying,
    active boolean,
    imagem text DEFAULT 'https://placehold.co/400x400'::text,
    evento_id bigint
);


ALTER TABLE public.itens OWNER TO postgres;

--
-- Name: itens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.itens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transacoes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transacoes (
    id bigint NOT NULL,
    tipo_pagamento character varying,
    email_telefone character varying,
    status smallint DEFAULT '0'::smallint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    valor numeric DEFAULT '0'::numeric,
    evento_id bigint DEFAULT '1'::bigint
);


ALTER TABLE public.transacoes OWNER TO postgres;

--
-- Name: transacoes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transacoes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transacoes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: arrecadacoes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--



--
-- Name: config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--



--
-- Name: eventos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--



--
-- Name: itens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--



--
-- Name: transacoes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--



--
-- Name: arrecadacoes arrecadacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arrecadacoes
    ADD CONSTRAINT arrecadacoes_pkey PRIMARY KEY (id);


--
-- Name: config config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.config
    ADD CONSTRAINT config_pkey PRIMARY KEY (id);


--
-- Name: eventos eventos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.eventos
    ADD CONSTRAINT eventos_pkey PRIMARY KEY (id);


--
-- Name: itens itens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.itens
    ADD CONSTRAINT itens_pkey PRIMARY KEY (id);


--
-- Name: transacoes transacoes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transacoes
    ADD CONSTRAINT transacoes_pkey PRIMARY KEY (id);


--
-- Name: arrecadacoes arrecadacoes_evento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arrecadacoes
    ADD CONSTRAINT arrecadacoes_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: arrecadacoes arrecadacoes_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arrecadacoes
    ADD CONSTRAINT arrecadacoes_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.itens(id);


--
-- Name: arrecadacoes arrecadacoes_transacao_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.arrecadacoes
    ADD CONSTRAINT arrecadacoes_transacao_id_fkey FOREIGN KEY (transacao_id) REFERENCES public.transacoes(id);


--
-- Name: itens itens_evento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.itens
    ADD CONSTRAINT itens_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public.eventos(id);


--
-- Name: transacoes transacoes_evento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transacoes
    ADD CONSTRAINT transacoes_evento_id_fkey FOREIGN KEY (evento_id) REFERENCES public.eventos(id);
